key: "Pause_Menu"

sprites:
  - sprite: "Content/Sprites/Interface/Menus/Pause_Menu_Background.png"
    position:
      - 0.5
      - 0.5
    z_order: 5000
    key: "Pause_Menu_Background"

buttons:
  - action:
      action: "remove_container"
      key: "Pause_Menu"
    position:
      - 0.5
      - 0.4
    z_order: 5001
    text: "Resume"
    text_z_order: 5002
    key: "Pause_Menu_Resume_Button"

  - action:
      action: "quit_game"
    position:
      - 0.5
      - 0.54
    z_order: 5001
    text: "Settings"
    text_z_order: 5002
    key: "Pause_Menu_Settings_Button"

  - action:
      action: "quit_game"
    position:
      - 0.5
      - 0.68
    z_order: 5001
    text: "Quit Game"
    text_z_order: 5002
    key: "Pause_Menu_Quit_Button"

text:
  - text: "Paused"
    text_size: 38
    text_color: [240, 240, 240]
    font: 'Content/Fonts/Comfortaa/Comfortaa-Regular.ttf'
    center_align: True
    position:
      - 0.5
      - 0.238
    z_order: 5003
    key: "Pause_Menu_Title"