EditorSettings:
  max_tabs: 3

EditorInterfaceSettings:
  toolbar_background_color: 44, 53, 57
  toolbar_button_background_color: 57, 67, 79

EditorTextSettings:
  header_font: "Helvetica"
  header_text_size: 12
  paragraph_font: "Helvetica"
  paragraph_text_size: 8
  button_font: "Helvetica"
  button_text_size: 10