EditorSettings:
  max_tabs: 3

EditorInterfaceSettings:
  toolbar_background_color: 44, 53, 57
  toolbar_button_background_color: 57, 67, 79
  details_button_background_color: 135, 148, 174

EditorTextSettings:
  header_1_font: "Helvetica"
  header_1_text_size: 12
  header_1_color: 0, 0, 0
  header_1_is_bold: True
  header_1_is_italicized: False

  header_2_font: "Helvetica"
  header_2_text_size: 11
  header_2_color: 0, 0, 0
  header_2_is_bold: False
  header_2_is_italicized: False

  header_3_font: "Helvetica"
  header_3_text_size: 16
  header_3_color: 96, 96, 96
  header_3_is_bold: False
  header_3_is_italicized: False

  paragraph_font: "Helvetica"
  paragraph_text_size: 8
  paragraph_color: 0, 0, 0
  paragraph_is_bold: False
  paragraph_is_italicized: False

  paragraph_2_font: "Helvetica"
  paragraph_2_text_size: 8
  paragraph_2_color: 96, 96, 96
  paragraph_2_is_bold: False
  paragraph_2_is_italicized: False

  subtext_font: "Helvetica"
  subtext_text_size: 8
  subtext_color: 96, 96, 96
  subtext_is_bold: False
  subtext_is_italicized: True

  button_font: "Helvetica"
  button_text_size: 10
  button_color: 0, 0, 0
  button_is_bold: False
  button_is_italicized: False

EditorStateSettings:
  read_only_background_color: 200, 200, 200
  selection_color: 180, 218, 244